### ISSUE TITLE
Error: Cannot read tile at coord 8, -1

### ISSUE THREAD

**Issue by loociano** [loociano/gb-ES6#2]
Steps to reproduce:

1. Start a Tetris game
2. Play until an horizontal (type I, or 4x1) tetrisminos appears.
3. Hit A to turn it vertical

The following exception is thrown (negative Y coordinate):
```
<error> Error: Cannot read tile at coord 8, -1
    at MMU.getCharCode (http://loociano.github.io/gb-ES6/gb-ES6.js:8870:15)
    at LCD._handleOBJAttributes (http://loociano.github.io/gb-ES6/gb-ES6.js:8138:32)
    at LCD.drawTile (http://loociano.github.io/gb-ES6/gb-ES6.js:8092:32)
    at LCD._drawOBJ (http://loociano.github.io/gb-ES6/gb-ES6.js:8034:16)
    at LCD.drawTiles (http://loociano.github.io/gb-ES6/gb-ES6.js:7977:14)
    at CPU._handleVBlankInterrupt (http://loociano.github.io/gb-ES6/gb-ES6.js:3239:16)
    at CPU.frame (http://loociano.github.io/gb-ES6/gb-ES6.js:3079:12)
    at CPU.start (http://loociano.github.io/gb-ES6/gb-ES6.js:3042:14)
    at frame (http://loociano.github.io/gb-ES6/gb-ES6.js:9637:7)
```

**Comment by loociano** [comment]
This is fixed in 0.0.3.
